trigger:
- main

pool:
  name: 'local-agent'

steps:
- script: |
    pwd
    whoami
    echo "Hello World!"
  displayName: 'hello script'
- script: |
    terraform --version
    terraform plan -out=tfplan
  displayName: 'Terraform Init and Plan'




#  terraform init -backend-config="storage_account_name=$(storageAccountName)" -backend-config="container_name=$(containerName)" -backend-config="key=$(key)" -backend-config="access_key=$(accessKey)"
# - stage: Deploy
#   displayName: 'Terraform Apply'
#   jobs:
#   - job: TerraformApply
#     displayName: 'Terraform Apply'
#     steps:
#     - task: TerraformInstaller@0
#       inputs:
#         terraformVersion: 'latest'

#     - script: |
#         terraform --version
#         terraform init -backend-config="storage_account_name=$(storageAccountName)" -backend-config="container_name=$(containerName)" -backend-config="key=$(key)" -backend-config="access_key=$(accessKey)"
#         terraform apply -auto-approve tfplan
#       displayName: 'Terraform Init and Apply'
