# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "newapp"
    vb.memory = "2048"
    vb.cpus = 1
  end

  config.vm.hostname = "newapp"

  config.vm.synced_folder ".", "/home/vagrant/code",
    owner: "www-data", group: "www-data"
  
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  
  config.vm.network "private_network", ip: "192.168.10.100"

  config.vm.provision "file", source: "./keys/.", destination: "$HOME/.ssh/"
  config.vm.provision "shell", path: "script.sh", privileged: false

end
